// Teste de registro de usuário
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nome": "teste1",
  "email": "teste1@example.com",
  "senha": "password123"
}

###

// Teste de login de usuário - obtendo token JWT
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "teste1@example.com",
  "senha": "password123"
}

###

// Teste de validação de token com token válido
GET http://localhost:3000/auth/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImVtYWlsIjoidGVzdGUyQHRlc3RlLmNvbSIsImlhdCI6MTc0MzM2ODA0NiwiZXhwIjoxNzQzNDU0NDQ2fQ.O-3AszvshhA7Z53MA7L3toKn31UKlr-ns1FkLZBLKzM

###

// Teste de validação de token com token inválido
GET http://localhost:3000/auth/validate
Content-Type: application/json
Authorization: Bearer invalidtoken123